version: '3.9'

services:
  blog:
    image: blog
    container_name: blog_app
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/code/static
      - .:/code/media
    depends_on:
      - postgres
    networks:
      - blog

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - blog_db:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    networks:
      - blog

networks:
  blog:
    driver: bridge

volumes:
    blog_db:
